[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataFramesMeta = "1313f7d8-7da2-5740-9ea0-a2ca25f37964"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
